"""Typed configuration for MoLAG commands."""

from ._constants import (
    CAMERA_HEIGHT_PIXELS,
    CAMERA_HORIZONTAL_FIELD_OF_VIEW_DEG,
    CAMERA_WIDTH_PIXELS,
    MAX_SCENE_GENERATION_ATTEMPTS,
    TRIANGULAR_TRACKER_BARYCENTRIC_TRANSFORM,
    TRIANGULAR_TRACKER_CANDIDATE_COORDINATES,
    TRIANGULAR_TRACKER_SIDE_LENGTH_MM,
)
from .args import Args, DatasetArgs, EvaluationArgs, LossArgs, ModelArgs, TrainingArgs

__all__ = [
    "Args",
    "DatasetArgs",
    "EvaluationArgs",
    "LossArgs",
    "ModelArgs",
    "TrainingArgs",
    "CAMERA_HEIGHT_PIXELS",
    "CAMERA_HORIZONTAL_FIELD_OF_VIEW_DEG",
    "CAMERA_WIDTH_PIXELS",
    "MAX_SCENE_GENERATION_ATTEMPTS",
    "TRIANGULAR_TRACKER_BARYCENTRIC_TRANSFORM",
    "TRIANGULAR_TRACKER_CANDIDATE_COORDINATES",
    "TRIANGULAR_TRACKER_SIDE_LENGTH_MM",
]
